feat: Frontend de lista, creación y detalles de hilos y comentarios #160
Galeon2098/CuidaME pull request #198
Opened 2024-03-21 22:14 UTC by fausto4VR

Se han hecho las vistas del frontend de lista, creación y detalles de hilos y comentarios. También he tocado algunas cosas que necesitaba para implementarlo, como añadiendo un apartado en la barra de navegación

2024-03-23 12:13 UTC, Lucperrom commented
-Arreglar Codacy (es solo un whitespace pero así ya te sale el check y se arregla rápido)
-Sonarcloud: mínimo arreglar la reliability
- Visualmente no está muy estético: arreglar el botón de añadir para que salga del mismo tamaño que crear hilo:
<img width="929" alt="image" src="https://github.com/Galeon2098/CuidaME/assets/100713036/3ac7fc1d-5af3-4fc8-bfaf-75b52a4b6202">

2024-03-23 12:49 UTC, Lucperrom commented
Fallo mío acabo de probar clonando el proyecto y sí se ve bien:
<img width="935" alt="image" src="https://github.com/Galeon2098/CuidaME/assets/100713036/c64d6f10-7752-4eae-8c68-42b3ec594bfc">

2024-03-23 12:52 UTC, Lucperrom commented
Se ve bien en cuanto arregles lo que te comentaba del codacy y el sonarcloud te acepto la pull request

2024-03-23 13:07 UTC, fausto4VR commented
Ya está corregido los fallos del codacy y del sonarcloud

2024-03-23 13:07 UTC, Lucperrom approved these changes
Ya está todo perfecto. Buen trabajo Fausto!

2024-03-23 13:41 UTC, crigarher commented
A la hora de crear hilo, el botón de atrás está un poco marginado, podrías incluirlo en el recuadro azul y con el icono de la flecha como está en otras vistas? Lo demás todo genial 😃

2024-03-23 23:29 UTC, fausto4VR commented
He cambiado los botones de atrás por un icono. Espero que así quede mejor. 
![Captura2](https://github.com/Galeon2098/CuidaME/assets/73647450/f1a39495-a23a-4077-91a4-5640f842c9f6)
![Captura](https://github.com/Galeon2098/CuidaME/assets/73647450/8962af44-40b7-4c81-812d-9331a7c3e53a)

2024-03-24 09:36 UTC, crigarher approved these changes
Todo ok 👍🏻 pero arregla el conflicto con el css

2024-03-24 09:37 UTC, crigarher requested changes
Arregla los conflictos del css porfi

2024-03-24 12:03 UTC, fausto4VR commented
Ya lo he corregido. Ahora no debería haber conflictos

2024-03-24 12:42 UTC, crigarher requested changes
Ahora sí todo bien :D

2024-03-24 12:43 UTC, crigarher approved these changes

2024-03-24 12:43 UTC, merged