Task#201 testing
Galeon2098/CuidaME pull request #259
Opened 2024-04-11 15:11 UTC by joaquin-restoy

![image](https://github.com/Galeon2098/CuidaME/assets/73226465/aa531e11-e32f-46d4-a362-aa7c0bd7bbb7)
Si se hace ejecutan los test de selenium de manera individual se consigue :
![image](https://github.com/Galeon2098/CuidaME/assets/73226465/30c962e2-9ce4-4472-ac1f-92163052ce09)

2024-04-11 16:56 UTC, Lucperrom commented
No puedo aceptar algo que no pase ni el build ni el codacy. Si los tests de selenium funcionan ejecutándolos por paquetes, pero no corriéndolos a la vez ajusta el action para que no corra los de selenium y corrige los errores del codacy porfa.

2024-04-11 21:15 UTC, Lucperrom approved these changes
Dado que los fallos del codacy no son en tu parte del código y son problemas menores, apruebo esta pr

2024-04-12 08:57 UTC, crigarher requested changes
![imagen_2024-04-12_105459238](https://github.com/Galeon2098/CuidaME/assets/80218587/e52cc7ed-f22c-46a8-944c-4de3e9fdbd56)
![image](https://github.com/Galeon2098/CuidaME/assets/80218587/f3945646-0156-4cf1-bf77-c969f87cc712)
Me da error en los test de selenium :/

2024-04-12 09:08 UTC, crigarher approved these changes
Fucionan los tests 👏🏻 😺

2024-04-12 09:08 UTC, merged